version: 2.1

orbs:
  python: circleci/python@1.3.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: sudo apt install python3.8
      - run: python3 -m pip install nox
      - run: python3 -m nox

workflows:
  main:
    jobs:
      - build-and-test
