on:
  push:
    branches:
      - main
  pull_request:
name: SQLAlchemy Spanner dialect
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install nox
        run: python -m pip install nox
      - name: Run Lint
        run: nox -s lint_setup_py lint blacken

  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install nox
        run: python -m pip install nox
      - name: Run Unit Tests
        run: nox -s unit
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: appdev-soda-spanner-staging

  compliance_tests_13:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install nox
        run: python -m pip install nox
      - name: Run Compliance Tests
        run: nox -s compliance_test_13
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: appdev-soda-spanner-staging

  compliance_tests_14:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install nox
        run: python -m pip install nox
      - name: Run Compliance Tests
        run: nox -s compliance_test_14
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: appdev-soda-spanner-staging
          SQLALCHEMY_SILENCE_UBER_WARNING: 1

  compliance_tests_20:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install nox
        run: python -m pip install nox
      - name: Run Compliance Tests
        run: nox -s compliance_test_20
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: appdev-soda-spanner-staging

  migration_tests:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install nox
        run: python -m pip install nox
      - name: Run Migration Tests
        run: nox -s migration_test
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: appdev-soda-spanner-staging

  migration1310_tests:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install nox
        run: python -m pip install nox
      - name: Run Migration Tests
        run: nox -s migration_test_1310
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: appdev-soda-spanner-staging
